#![allow(non_snake_case)]
use anyhow::{bail, Context, Result};
use std::sync::{Arc,LazyLock,RwLock,atomic::{AtomicBool,Ordering}};
use tokio::{io::{AsyncBufReadExt,BufReader},net::UdpSocket,sync::mpsc};
use tokio_util::sync::CancellationToken;
use wdtt_rslib::{dispatcher::NewDispatcher,events::{emitConfig,emitEvent,eventStarted,eventStopped},profiles::SetActiveFingerprint,stats::NewStats,worker_group::{ParseHashes,TurnParams,WorkerGroup,workersPerGroup},wrap::deriveWrapKey};

static captchaModeValue:LazyLock<RwLock<String>>=LazyLock::new(||RwLock::new("auto".into())); static vkAuthModeValue:LazyLock<RwLock<String>>=LazyLock::new(||RwLock::new("vkcalls".into()));
pub fn normalizeCaptchaMode(mode:&str)->String{match mode.trim().to_lowercase().as_str(){"auto"|"rjs"|"wv"=>mode.trim().to_lowercase(),_=>"auto".into()}} pub fn setCaptchaMode(mode:&str)->String{let x=normalizeCaptchaMode(mode);*captchaModeValue.write().unwrap()=x.clone();x} pub fn getCaptchaMode()->String{captchaModeValue.read().unwrap().clone()} pub fn normalizeVKAuthMode(mode:&str)->String{if mode.trim().eq_ignore_ascii_case("legacy"){"legacy".into()}else{"vkcalls".into()}} pub fn setVKAuthMode(mode:&str)->String{let x=normalizeVKAuthMode(mode);*vkAuthModeValue.write().unwrap()=x.clone();x} pub fn getVKAuthMode()->String{vkAuthModeValue.read().unwrap().clone()}

#[derive(Default)] struct Args { turn:String,port:String,listen:String,vk:String,peer:String,n:usize,device_id:String,password:String,obfs:String,fingerprint:String,captcha:String,vk_auth:String,client_ids:String }
fn args()->Result<Args>{let mut a=Args{listen:"127.0.0.1:9000".into(),n:24,device_id:"unknown".into(),obfs:"audio".into(),fingerprint:"chrome".into(),captcha:"auto".into(),vk_auth:"vkcalls".into(),..Default::default()};let mut it=std::env::args().skip(1);while let Some(k)=it.next(){let v=it.next().with_context(||format!("нет значения для {k}"))?;match k.as_str(){"-turn"=>a.turn=v,"-port"=>a.port=v,"-listen"=>a.listen=v,"-vk"=>a.vk=v,"-peer"=>a.peer=v,"-n"=>a.n=v.parse().context("-n")?,"-device-id"=>a.device_id=v,"-password"=>a.password=v,"-obfs"=>a.obfs=v,"-fingerprint"=>a.fingerprint=v,"-captcha-mode"=>a.captcha=v,"-vk-auth-mode"=>a.vk_auth=v,"-client-ids"=>a.client_ids=v,_=>bail!("неизвестный аргумент: {k}")}}Ok(a)}

#[tokio::main] async fn main()->Result<()> { let a=args()?; if a.peer.is_empty()||a.vk.is_empty(){bail!("Нужны -peer и -vk")} if a.password.is_empty(){bail!("Нужен -password")}; let hashes=ParseHashes(&a.vk);if hashes.is_empty(){bail!("Нет хешей VK")};SetActiveFingerprint(&a.fingerprint);setCaptchaMode(&a.captcha);setVKAuthMode(&a.vk_auth);if !a.client_ids.is_empty(){wdtt_rslib::vk_auth::SetActiveClientIds(&a.client_ids)}let key=deriveWrapKey(&a.password)?;let workers=a.n.clamp(workersPerGroup,108)/workersPerGroup*workersPerGroup;let socket=UdpSocket::bind(&a.listen).await.with_context(||format!("бинд {}",a.listen))?;let port=socket.local_addr()?.port().to_string();let stats=Arc::new(NewStats());let dispatcher=NewDispatcher(socket,stats.clone()).await;tokio::spawn(dispatcher.clone().readLoop());tokio::spawn(dispatcher.clone().writeLoop());let cancel=CancellationToken::new();let paused=Arc::new(AtomicBool::new(false));let(config_tx,mut config_rx)=mpsc::channel(1);let params=Arc::new(TurnParams{Host:a.turn,Port:a.port,Hashes:hashes,WrapKey:key,ObfsMode:a.obfs});eprintln!("[КЛИЕНТ] Слушаю {} | пир {} | воркеров {}",port,a.peer,workers);emitEvent(eventStarted,serde_json::json!({"listen_port":port,"workers":workers}));for group in 0..workers/workersPerGroup { let ids=(0..workersPerGroup).map(|n|(group*workersPerGroup+n)as i32).collect();tokio::spawn(WorkerGroup(cancel.clone(),group as i32,group,params.clone(),a.peer.clone(),dispatcher.clone(),port.clone(),group==0,config_tx.clone(),ids,paused.clone(),a.device_id.clone(),a.password.clone(),stats.clone())); }
let stdin_cancel=cancel.clone();let stdin_pause=paused.clone();tokio::spawn(async move {let mut lines=BufReader::new(tokio::io::stdin()).lines();while let Ok(Some(line))=lines.next_line().await{match line.trim(){"PAUSE"=>stdin_pause.store(true,Ordering::Relaxed),"RESUME"=>stdin_pause.store(false,Ordering::Relaxed),"STOP"=>{stdin_cancel.cancel();break},_=>{}}}});let event_cancel=cancel.clone();tokio::spawn(async move {while let Some(config)=config_rx.recv().await{emitConfig(&config);}});tokio::select!{_=tokio::signal::ctrl_c()=>cancel.cancel(),_=cancel.cancelled()=>{}};dispatcher.Shutdown().await;emitEvent(eventStopped,serde_json::json!({}));Ok(()) }
